### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by kushagra765** [Platypus-Tech/platypus-os#20]
I tried to manually compile the OS by using `gcc` and `as`. The folder arch/i386 compiles successfully.

But the folder kernel/devices gives errors :
`atkbd.c : <asm/delay.h> No such file`

ps2mouse.c :
```
ps2mouse.c : ps2mouse.h:13:10: error: field ‘init_mouse’ declared as a function
   13 |     void init_mouse();
      |          ^~~~~~~~~~
ps2mouse.h:14:10: error: field ‘work_mouse’ declared as a function
   14 |     void work_mouse();
      |          ^~~~~~~~~~
```

**Comment by DamieFC** [comment]
Ok, I'm going to work on that.

**Comment by kushagra765** [comment]
The `<asm/delay.h>` is required by `<linux/delay.h>`. So, if you add the asm/delay.h header in /include/asm/ , it will work.

**Comment by DamieFC** [comment]
Yeah, I got rid of the `atkbd.c` and `hpps2atkbd.h` files (I don't need them anymore), and I'm going to fix the PS/2 mouse driver now.

**Comment by kushagra765** [comment]
This issue should be closed now. I have fixed the ps2mouse.c errors, but you can see the file if you want.

**Comment by DamieFC** [comment]
Ok
