### ISSUE TITLE
Keyboard Driver Code Issue 

### ISSUE THREAD

**Issue by kushagra765** [Platypus-Tech/platypus-os#21]
Functions inside a `struct` won't work and will give an error during compilation.

**Comment by kushagra765** [comment]
I can add the keyboard driver from my OS if you want.

**Comment by DamieFC** [comment]
sure! go ahead!

**Comment by kushagra765** [comment]
Ok

**Comment by DamieFC** [comment]
I reopened to remind myself.

**Comment by DamieFC** [comment]
Rewrite going to happen.
