### ISSUE TITLE
Porting PDCLIB

### ISSUE THREAD

**Issue by kushagra765** [Platypus-Tech/platypus-os#28]

**Comment by DamieFC** [comment]
?

**Comment by kushagra765** [comment]
I tried to port Public Domain C Library (PDCLIB).

**Comment by kushagra765** [comment]
You can delete this issue if you want.

**Comment by kushagra765** [comment]
> I tried to port Public Domain C Library (PDCLIB).

It wasn't working so I removed it from the OS.

**Comment by DamieFC** [comment]
Ok
