### ISSUE TITLE
Port ncurses or something similar

### ISSUE THREAD

**Issue by DamieFC** [Platypus-Tech/platypus-os#32]
Would be cool so we can have a user interface, obviously sometime in the future

**Comment by kushagra765** [comment]
To port ncurses, we need a C Library, a terminal like Bash and Coreutils.

**Comment by DamieFC** [comment]
Yeah

**Comment by kushagra765** [comment]
So, we should start with the C Library

**Comment by DamieFC** [comment]
Yep!

**Comment by kushagra765** [comment]
Ok

**Comment by kushagra765** [comment]
Which C Library should we port?

**Comment by kushagra765** [comment]
Can we port [TermBox](https://github.com/nsf/termbox) instead of ncurses?

**Comment by DamieFC** [comment]
Sure!

**Comment by DamieFC** [comment]
*rolls eyes up in head, sticks tongue out at bot*
