### ISSUE TITLE
Build error (ugh)

### ISSUE THREAD

**Issue by DamieFC** [Platypus-Tech/platypus-os#56]
This may have something to do with the terminal being added.
![2021-06-05-152128_800x480_scrot](https://user-images.githubusercontent.com/69485115/120906890-01646600-c612-11eb-8800-98c4cb407819.png)

**Comment by DamieFC** [comment]
I'm on a raspberry pi, normally I'm on a chromebook.

**Comment by DamieFC** [comment]
Still fudged up: 
![2021-06-06-161917_800x480_scrot](https://user-images.githubusercontent.com/69485115/120943310-03e2c080-c6e3-11eb-8d17-6a7e90e5ff5a.png)

**Comment by kushagra765** [comment]
This issue should be closed now.

**Comment by DamieFC** [comment]
Ok, I still need to test it

**Comment by DamieFC** [comment]
Well, the screenshot shows it's working, so I'll close it
