### ISSUE TITLE
Build Failing 

### ISSUE THREAD

**Issue by kushagra765** [Platypus-Tech/platypus-os#61]
Build failing

**Comment by DamieFC** [comment]
![2021-06-13-104141_800x480_scrot](https://user-images.githubusercontent.com/69485115/121817067-fa51df00-cc33-11eb-9f79-4ff4f485b791.png)
This is what I get

**Comment by kushagra765** [comment]
The terminal is fixed. It's working.

**Comment by kushagra765** [comment]
Build error.
