### ISSUE TITLE
Memory manager

### ISSUE THREAD

**Issue by DamieFC** [Platypus-Tech/platypus-os#9]
In commit 5be1190, I asked for help when deleting my bad manager. Help!

**Comment by kushagra765** [comment]
Ok. I will try to implement a memory manager.

**Comment by DamieFC** [comment]
yay!

**Comment by kushagra765** [comment]
Added memory manager.

**Comment by kushagra765** [comment]
You can close this issue.

**Comment by DamieFC** [comment]
Ok!
